version: "3.8"
services:
  web:
    tty: true
    stdin_open: true
    build:
      dockerfile: ./docker_dev/Dockerfile
      context: .
    volumes:
      - .:/app
      - bundle_volume:/bundle
      - ~/.gem:/root/.local/share/gem
    env_file:
      - ./docker_dev/.env_docker

volumes:
  bundle_volume:
    driver: local
